#+TITLE: Requirements: Measuring the energy consumption of AI
#+AUTHOR: Danilo Carastan-Santos

* Hardware/Sofware Requirements
1) Intel CPU
2) Linux OS (Tested on Ubuntu) with superuser (i.e., ~sudo~) permissions
3) NVIDIA GPU (Not used in the session)
4) TensorFlow (tested on version 2.9.0)
5) CodeCarbon
6) Git

Most energy measurement software rely on Intel's RAPL interface to obtain CPU
and energy data.  In Linux, one way to access the RAPL interface is via the
~powercap~ framework
([[https://www.kernel.org/doc/html/latest/power/powercap/powercap.html]]).  For
the hands-on session, you must the able to access RAPL by the following command

#+begin_src bash
sudo cat /sys/class/powercap/intel-rapl/intel-rapl:0/energy_uj
#+end_src

The ~sudo~ became necessary as a patch to avoid a security vulnerability with
the RAPL interface
([[https://www.intel.com/content/www/us/en/developer/articles/technical/software-security-guidance/advisory-guidance/running-average-power-limit-energy-reporting.html]])

To avoid additional requirements, the session does not cover monitoring the GPU
energy consumption. The way we monitor the energy consumption with CodeCarbon is
the same for CPU and GPU. If you want to use GPUs CodeCarbon only supports
NVIDIA GPUs, and you should be able to run Tensorflow with GPU support
([[https://www.tensorflow.org/install/pip]])

* Installation procedure

This part assumes that you are used to using a terminal.
Open a terminal, then run the following commands

** 1. Create a directory to clone this repository

#+begin_src shell
mkdir measuring-energy-ai-tutorial
cd measuring-energy-ai-tutorial
#+end_src

** 2. Clone this repository

#+begin_src shell
git clone https://github.com/danilo-carastan-santos/ai-energy-consumption.git
#+end_src

** 3. Create and activate a Python virtual environment

#+begin_src shell
cd ai-energy-consumption
python3 -m venv venv/
source venv/bin/activate
#+end_src

** 4. Install the software requirements

#+begin_src shell
pip install --upgrade pip
pip install -r requirements.txt
#+end_src

** 5. Enable access to perf-events data without administrator rights

This step is required to run Alumet (section 1d). Without this section 1d will not work.

#+BEGIN_SRC shell
sudo sysctl -w kernel.perf_event_paranoid=0
#+END_SRC

~kernel.perf_event_paranoid~ ranges from -1 to 2 (source: [[https://www.kernel.org/doc/Documentation/sysctl/kernel.txt]]).
Setting it to 0 is sufficient for Alumet. You can revert by setting it to 2, for instance. 

** 6. Run session.py as test

#+begin_src shell
sudo venv/bin/python session.py --sect 1b
#+end_src

If you have sudo permissions, CodeCarbon will use the ~powercap~ interface to collect RAPL data.

If you don't have ~sudo~ permissions, CodeCarbon (sections 1b, 1c, and 2a) will run in TDP mode.
It will search for the TDP of your processor, or it will fall back to a default TDP of 85W.
Then, it will estimate the energy consumption by dividing the TDP by 2 
(assuming an average utilization of 50%), and multiplying by the processing time.

Sources:
- [[https://github.com/mlco2/codecarbon/blob/6391b66c7947b06d48e485b99da32816390c865d/codecarbon/external/hardware.py#L161]]
- [[https://github.com/mlco2/codecarbon/blob/6391b66c7947b06d48e485b99da32816390c865d/codecarbon/external/hardware.py#L226]]
- [[https://github.com/mlco2/codecarbon/blob/6391b66c7947b06d48e485b99da32816390c865d/codecarbon/external/hardware.py#L21]]

** Observations
- Once inside the virtual environment, you can run the ~deactivate~ command to
disconnect from the virtual environment.
- There are five sections ~(1a, 1b, 1c, 1d, 2a)~, each of which presents new
  concepts and propose questions ~(Q1, Q2, Q3, Q4, Q5, Q6, Q7)~. These questions
  will be explored during the hands-on session. You can run a different section
  by using the ~--sect~ argument in the command at step 5.
- The questions can be seen at the ~session.py~ as comments. Inside a terminal
  you can use the ~nano~ editor (i.e., command ~nano session.py~) to navigate
  and edit the source code.
